### ISSUE TITLE
Crash on Linux with sigsegv

### ISSUE THREAD

**Issue by Neubulae** [Axeryok/CocoaInput#12]
[hs_err_pid1995612.log](https://github.com/Axeryok/CocoaInput/files/6715930/hs_err_pid1995612.log)
[latest.log](https://github.com/Axeryok/CocoaInput/files/6715932/latest.log)

**Comment by Axeryok** [comment]
Tell me what IMF and IME you use.
For now, use 4.0.4 version, turn AdvancedPreeditDraw to false from Config Screen and try to input some characters.
Possibly you can avoid crash.

**Comment by Neubulae** [comment]
> Tell me what IMF and IME you use.
> For now, use 4.0.4 version, turn AdvancedPreeditDraw to false from Config Screen and try to input some characters.
> Possibly you can avoid crash.

fcitx5 5.0.8-1 with fcitx5-rime 5.0.6-1
Using your method, the crash is successfully avoided. Thanks!
